version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php-fpm
    environment:
      - DOPPLER_TOKEN
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
